# Name of calibration to be used in output table
name: mode5

# Configuration of directories
singles_dir: /mnt/jype/MainSurvey/reduced
tiles_dir: /mnt/jype/MainSurvey/tiles/T01
#main_dir: /mnt/public/kadu/stdcal
main_dir: /home/kadu/Dropbox/SPLUS/stdcal/stdcal

# Select interval of nights used in the calibration
first_night: 2017-12-14
last_night: 2030-01-01

# Parameters for the cutout
cutout_size: 200 # pixel

# Sextractor-related configurations
sex_redo: False # Option to overwrite sextractor catalog

# Photometry type with SExtractor
sex_phot:
- FLUX_AUTO
- FLUX_APER

# Tolerance of matching in the coordinates
rtol: 5 # pixel

# Library to be used in the calibration
stdlib: ctiostan # ctiostan, hststan, okestan, wdstan

# Version of the transmission curve
filters_version: dr1 # dr1 or dr2

# List of problematic stars that should be skipped in the calibration
# Names are case insensitive
flagged_stars:
# - "LTT 377" # High proper-motion star; model seems to be incorrect
#- "LTT 3218" # White Dwarf
#- "LTT 4364" #  White Dwarf
#- "CD-32_9927"
- "HR 7950" # * eps Aqr, mag~3, probably saturated
- "HR 4468" # * tet Crt, High proper-motion Star, mag~4.6, probably saturated




